services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      - 'POSTGRES_USER=${PG_USER}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_DB=${PG_DATABASE_NAME}'
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - '${PG_PORT}:5432'

volumes:
  redis_data:
  postgres_data:
